Result <-
list(AKMmono02 = structure(c(31L, 2L, 594L, 9L, 8L, 0L, 0L, 8L, 
0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
"-2", "0", "1", NA), c("T", NA)), .Names = c("", "")), class = "table"), 
    AKMmono03 = structure(c(0L, 0L, 0L, 1L, 0L, 0L, 169L, 21L, 
    18L, 1870L, 19L, 17L, 6L, 1L, 0L, 142L, 0L, 0L), .Dim = c(6L, 
    3L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", NA), c("-", "A", NA)), .Names = c("", "")), class = "table"), 
    AKMmono05 = structure(c(51L, 10L, 281L, 10L, 4L, 3L, 0L, 
    32L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("A", NA)), .Names = c("", 
    "")), class = "table"), AKMmono13 = structure(c(31L, 2L, 
    433L, 6L, 1L, 2L, 0L, 32L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("A", NA)), .Names = c("", 
    "")), class = "table"), AKMmono16 = structure(c(45L, 3L, 
    682L, 11L, 3L, 0L, 0L, 36L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("A", NA)), .Names = c("", 
    "")), class = "table"), AKMmono22 = structure(c(30L, 6L, 
    365L, 9L, 14L, 0L, 0L, 1L, 0L, 0L, 2L, 0L, 37L, 1L, 0L), .Dim = c(5L, 
    3L), .Dimnames = structure(list(c("-1", "-2", "0", "1", NA
    ), c("A", "G", NA)), .Names = c("", "")), class = "table"), 
    EJmono05 = structure(c(98L, 13L, 970L, 12L, 2L, 1L, 0L, 27L, 
    1L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("T", NA)), .Names = c("", "")), class = "table"), 
    EJmono16 = structure(c(129L, 3L, 1L, 1702L, 108L, 5L, 44L, 
    0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 21L, 0L, 0L, 0L), .Dim = c(7L, 
    3L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", "2", NA), c("A", "G", NA)), .Names = c("", "")), class = "table"), 
    LMmono01 = structure(c(40L, 2L, 441L, 8L, 3L, 1L, 0L, 19L, 
    1L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("A", NA)), .Names = c("", "")), class = "table"), 
    LMmono03 = structure(c(40L, 4L, 131L, 4L, 4L, 0L, 0L, 7L, 
    0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("C", NA)), .Names = c("", "")), class = "table"), 
    LMmono09 = structure(c(97L, 13L, 449L, 21L, 4L, 1L, 0L, 6L, 
    0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("T", NA)), .Names = c("", "")), class = "table"), 
    LMmono12 = structure(c(142L, 11L, 1007L, 58L, 4L, 1L, 34L, 
    1L, 0L, 29L, 0L, 0L, 0L, 0L), .Dim = c(7L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", "2", "3", NA), c("A", NA)), .Names = c("", 
    "")), class = "table"), LMmono16 = structure(c(52L, 1L, 329L, 
    26L, 2L, 1L, 4L, 2L, 0L, 50L, 1L, 0L, 0L, 0L), .Dim = c(7L, 
    2L), .Dimnames = structure(list(c("-1", "-2", "0", "1", "2", 
    "3", NA), c("A", NA)), .Names = c("", "")), class = "table"), 
    MSJmono10 = structure(c(0L, 0L, 1L, 0L, 0L, 83L, 2L, 1449L, 
    43L, 7L, 2L, 0L, 40L, 2L, 0L), .Dim = c(5L, 3L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("A", "C", NA)), .Names = c("", 
    "")), class = "table"), MSJmono19ms1 = structure(c(74L, 7L, 
    1708L, 38L, 2L, 23L, 0L, 0L, 1L, 0L, 0L, 0L, 10L, 0L, 204L, 
    5L, 0L, 0L), .Dim = c(6L, 3L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", "2", NA), c("A", "T", NA)), .Names = c("", 
    "")), class = "table"), MSJmono19ms2 = structure(c(0L, 1L, 
    0L, 0L, 76L, 1667L, 45L, 19L, 1L, 114L, 1L, 0L), .Dim = 4:3, .Dimnames = structure(list(
        c("-1", "0", "1", NA), c("A", "C", NA)), .Names = c("", 
    "")), class = "table"), MSJmono36 = structure(c(130L, 7L, 
    179L, 19L, 1L, 6L, 0L, 0L, 7L, 0L, 0L, 0L), .Dim = c(6L, 
    2L), .Dimnames = structure(list(c("-1", "-2", "0", "1", "3", 
    NA), c("G", NA)), .Names = c("", "")), class = "table"), 
    MSJmono44 = structure(c(17L, 1L, 284L, 5L, 2L, 1L, 0L, 5L, 
    0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("T", NA)), .Names = c("", "")), class = "table"), 
    MSJmono46 = structure(c(19L, 8L, 100L, 7L, 4L, 0L, 0L, 9L, 
    0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("C", NA)), .Names = c("", "")), class = "table"), 
    LMmono04v2_SNP1 = structure(c(1L, 1L, 0L, 12L, 192L, 10L, 
    0L, 19L, 2L), .Dim = c(3L, 3L), .Dimnames = structure(list(
        c("-1", "0", "1"), c("C", "T", NA)), .Names = c("", ""
    )), class = "table"), AKMmono01v2_SNP1 = structure(c(53L, 
    4L, 660L, 5L, 3L, 1L, 0L, 12L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("T", NA)), .Names = c("", 
    "")), class = "table"), AKMmono10v2_SNP1 = structure(c(11L, 
    0L, 224L, 2L, 0L, 22L, 1L, 396L, 1L, 2L, 0L, 0L, 33L, 1L, 
    0L), .Dim = c(5L, 3L), .Dimnames = structure(list(c("-1", 
    "-2", "0", "1", NA), c("A", "G", NA)), .Names = c("", "")), class = "table"), 
    AKMmono17v2_SNP1 = structure(c(5L, 0L, 52L, 1L, 0L, 5L, 1L, 
    80L, 1L, 1L, 0L, 0L, 7L, 0L, 0L), .Dim = c(5L, 3L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("A", "C", NA)), .Names = c("", 
    "")), class = "table"), EJmono13v2_SNP1 = structure(c(9L, 
    224L, 5L, 1L, 11L, 210L, 7L, 2L, 0L, 14L, 0L, 0L), .Dim = 4:3, .Dimnames = structure(list(
        c("-1", "0", "1", NA), c("A", "G", NA)), .Names = c("", 
    "")), class = "table"), LMmono05v2_SNP1 = structure(c(10L, 
    1L, 119L, 1L, 1L, 8L, 1L, 77L, 3L, 0L, 1L, 0L, 5L, 0L, 0L
    ), .Dim = c(5L, 3L), .Dimnames = structure(list(c("-1", "-2", 
    "0", "1", NA), c("A", "T", NA)), .Names = c("", "")), class = "table"), 
    LMmono10v2_SNP1 = structure(c(103L, 10L, 1L, 743L, 18L, 25L, 
    1L, 2L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 30L, 0L, 0L), .Dim = c(6L, 
    3L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", NA), c("A", "G", NA)), .Names = c("", "")), class = "table"), 
    MSJmono30v2_SNP1 = structure(c(7L, 110L, 3L, 3L, 42L, 2L, 
    0L, 71L, 8L), .Dim = c(3L, 3L), .Dimnames = structure(list(
        c("-1", "0", "1"), c("C", "T", NA)), .Names = c("", ""
    )), class = "table"), EJmono14v2_SNP1 = structure(c(11L, 
    0L, 183L, 0L, 1L, 1L, 22L, 1L, 231L, 1L, 0L, 0L, 3L, 0L, 
    49L, 1L, 0L, 0L), .Dim = c(6L, 3L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", "2", NA), c("A", "G", NA)), .Names = c("", 
    "")), class = "table"), AKMmono08v2_SNP1 = structure(c(8L, 
    1L, 283L, 13L, 0L, 0L, 1L, 0L, 0L, 0L, 11L, 0L), .Dim = 4:3, .Dimnames = structure(list(
        c("-1", "-2", "0", "1"), c("A", "G", NA)), .Names = c("", 
    "")), class = "table"), EJmono10 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LMmono02 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LMmono07 = structure(c(20L, 1L, 243L, 
    6L, 3L, 0L, 0L, 11L, 1L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("G", NA)), .Names = c("", 
    "")), class = "table"), AKMmono15 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), EJmono15 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), MSJmono24 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AKMmono18 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), EJmono08 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AKMmono06 = structure(c(137L, 18L, 
    1L, 1L, 525L, 44L, 6L, 28L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 8L, 0L, 0L, 0L), .Dim = c(8L, 3L), .Dimnames = structure(list(
        c("-1", "-2", "-3", "-4", "0", "1", "2", NA), c("A", 
        "G", NA)), .Names = c("", "")), class = "table"), EJmono04 = structure(c(155L, 
    11L, 2L, 805L, 51L, 2L, 41L, 2L, 0L, 0L, 37L, 1L, 0L, 0L), .Dim = c(7L, 
    2L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", "2", NA), c("G", NA)), .Names = c("", "")), class = "table"), 
    EJmono02 = structure(c(6L, 198L, 4L, 0L, 17L, 0L), .Dim = 3:2, .Dimnames = structure(list(
        c("-1", "0", NA), c("T", NA)), .Names = c("", "")), class = "table"), 
    EJmono06v2_SNP1 = structure(c(57L, 8L, 4L, 144L, 16L, 2L, 
    38L, 34L, 7L, 1L, 88L, 6L, 1L, 14L, 29L, 1L, 3L, 263L, 10L, 
    3L, 0L), .Dim = c(7L, 3L), .Dimnames = structure(list(c("-1", 
    "-2", "-3", "0", "1", "2", NA), c("A", "G", NA)), .Names = c("", 
    "")), class = "table"), EJmono03 = structure(c(41L, 2L, 453L, 
    6L, 2L, 0L, 0L, 19L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("C", NA)), .Names = c("", 
    "")), class = "table"), MSJmono23v2_SNP1 = structure(c(4L, 
    1L, 3L, 0L, 1L, 0L, 29L, 1L, 0L, 0L, 3L, 0L), .Dim = 4:3, .Dimnames = structure(list(
        c("-1", "-2", "0", "1"), c("G", "T", NA)), .Names = c("", 
    "")), class = "table"), EJmono12 = structure(c(179L, 15L, 
    1L, 1070L, 39L, 5L, 0L, 0L, 0L, 148L, 2L, 0L), .Dim = c(6L, 
    2L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", NA), c("C", NA)), .Names = c("", "")), class = "table"), 
    LSWGSmono03 = structure(integer(0), .Dim = c(0L, 0L), .Dimnames = structure(list(
        NULL, NULL), .Names = c("", "")), class = "table"), LSWGSmono04 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono07 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono08 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono09 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono18 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono19 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono23 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono25 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono26 = structure(c(40L, 4L, 
    131L, 4L, 4L, 0L, 0L, 7L, 0L, 0L), .Dim = c(5L, 2L), .Dimnames = structure(list(
        c("-1", "-2", "0", "1", NA), c("C", NA)), .Names = c("", 
    "")), class = "table"), LSWGSmono28 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono31 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), LSWGSmono32 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AAAG0701_SNP1 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AAAG0904_SNP1 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AAAG1103_SNP1 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), AGAT0702_SNP1 = structure(integer(0), .Dim = c(0L, 
    0L), .Dimnames = structure(list(NULL, NULL), .Names = c("", 
    "")), class = "table"), GM07_SNP1 = structure(c(40L, 531L, 
    13L, 1L, 5L, 30L, 766L, 15L, 0L, 6L, 1L, 37L, 2L, 0L, 0L), .Dim = c(5L, 
    3L), .Dimnames = structure(list(c("-1", "0", "1", "2", NA
    ), c("A", "G", NA)), .Names = c("", "")), class = "table"), 
    LR44_SNP1 = structure(c(0L, 3L, 0L, 0L, 14L, 234L, 1L, 1L, 
    0L, 5L, 0L, 0L), .Dim = 4:3, .Dimnames = structure(list(c("-1", 
    "0", "1", NA), c("C", "T", NA)), .Names = c("", "")), class = "table"), 
    LR52_SNP1 = structure(c(0L, 0L, 0L, 7L, 0L, 0L, 62L, 5L, 
    1L, 760L, 4L, 9L, 3L, 0L, 0L, 70L, 1L, 0L), .Dim = c(6L, 
    3L), .Dimnames = structure(list(c("-1", "-2", "-3", "0", 
    "1", NA), c("C", "T", NA)), .Names = c("", "")), class = "table"))
